require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/MethodLength:
  Max: 15
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
