require: rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
Style/Documentation:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Naming/VariableNumber:
  EnforcedStyle: snake_case
Style/ExponentialNotation:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/MixinUsage:
  Exclude:
    - bin/setup
Style/Next:
  MinBodyLength: 5
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SignalException:
  EnforcedStyle: semantic
Style/SlicingWithRange:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
Metrics/MethodLength:
  Max: 15
